### ISSUE TITLE
Newsletter post from numfys

### ISSUE THREAD

**Issue by minrk** [jupyter/newsletter#13]
At NTNU, I talked to @hwagit about doing a guest post on [numfys](http://numfys.net). This newsletter seems like a great way to do it. Opening this issue to get the ball rolling.

**Comment by hakonanes** [comment]
Yes, it would be great to contribute with a blog post or something similar in your newsletter. 

We (@askrogen, @komperter and I) think it might be interesting to talk about how the NumFys project and physics students at [NTNU](http://www.ntnu.edu/physics) use the Jupyter Notebook when solving numerical exercises, or presenting a numerical technique.

But we are also happy to take suggestions.

**Comment by Ruv7** [comment]
We're pulling together content for this now, any chance we can get this by tomorrow the 22nd? The ideal format is a couple of sentences to highlight ending with a link to a full story. If it doesn't make it into this next edition we can always put it in future newsletters...

**Comment by willingc** [comment]
Electrical engineers and open hardware folks will like this notebook: http://numfys.net/media/files/examples/html/4.1_Resistor_Network_ASTUF5W.html

**Comment by hakonanes** [comment]
What is the ideal length of the full story? I'm afraid we can't put it down as soon as tomorrow, the next newsletter might be better.

It might be a good idea to highlight a few notebooks, e.g. the resistor network one.

**Comment by Ruv7** [comment]
Ok, that works. Whatever you believe is easy to digest by the reader in a single blog post. This depends on the complexity of the content and the preferences of the reader so I don't have a quick answer on that one. If you think it's too much for one post and this is powerful content then you can submit multiple items and they can be used as there is space in the newsletters... Since I'm not a technical person (I'm a Marketer/Operations ninja) I will leave it to you to decide what makes sense and look to the engineers on the team to confirm what you suggest makes sense.

**Comment by katiewhite360** [comment]
We really only need the topic tomorrow...if we could get a short paragraph and link by Friday it could be published in this newsletter. I would love to use this as the featured use case/user section...

**Comment by hakonanes** [comment]
> With the goal of becoming a natural resource for physics students at the Norwegian University of Science and Technology, the NumFys project makes numerical physics learning modules and examples using the Jupyter Notebook. Most of the notebooks are made by students, and everything is available at [numfys.net](http://numfys.net).

How does this look as an introduction? Do you need an image, logo or anything else?

**Comment by katiewhite360** [comment]
Could I get a 5-10  word header and an image? That would be fantastic.

**Comment by hakonanes** [comment]
Header: 

> Learning numerical physics with Jupyter Notebook

Here is the logo ([numfys_logo_white.pdf](https://github.com/jupyter/newsletter/files/186802/numfys_logo_white.pdf)) and a screen shot from a notebook on Lagrange points in the Sun Earth system ([numfys_lagrange_points.png](https://cloud.githubusercontent.com/assets/12139781/14001084/a07f8b50-f144-11e5-85fe-3e29f4cb618c.png)).

**Comment by willingc** [comment]
Closing this issue since published in newsletter [here](https://newsletter.jupyter.org/jupyter-newsletter-2-march-30-e73bdefd185f#.20z8yefs7). Great project @hwagit 👍
