### ISSUE TITLE
Peter did it again

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#14]
A notebook to introduce probability by peter norvig:

Peter Norvig is now famous for writing well though and detailed notebooks walking the reader through interesting problems. We are one again bless by a beautiful introduction to probability using Python, and slowly build-up – using some basics programming skills – intuitions on how probability theory works. 

http://nbviewer.jupyter.org/url/norvig.com/ipython/Probability.ipynb

**Comment by Carreau** [comment]
@katiewhite360 Updated this one as well.

**Comment by katiewhite360** [comment]
Nice
