### ISSUE TITLE
JupyterDays Boston recap

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#15]
Cf @willingc tweet:

https://twitter.com/WillingCarol/status/710907619376902144

Nice summary of JupyterDays from @dbouquin:

http://altbibl.io/gazette/jupyterdays-day-1/ 

I have to find the link for day 2...

[update]
http://altbibl.io/gazette/jupyterdays-day-2/

---

Last Jupyter Days were hold on March 17 and 18 at the Harvard Center for Astrophysics, and generously sponsored by O'Reilly media. `@dbouquin`, one of our fellow volunteers have written nice writeups that summarize each of the 2 days. We hope to see you at next JupyterDays, who know you might be the organizers next time !

**Comment by rgbkrk** [comment]
It was awesome.

**Comment by Ruv7** [comment]
I don't think Daina from the Astrophysics library has written it yet... but yes this was awesome!

**Comment by dbouquin** [comment]
Day two is getting posted tonight! Will add the link here. Got delayed but will get done.

**Comment by dbouquin** [comment]
Sorry for the delay all. Day two is up! @Carreau @Ruv7 @rgbkrk 
 http://altbibl.io/gazette/jupyterdays-day-2/

**Comment by rgbkrk** [comment]
Thank you so much for the writeup! I stayed way too active talking with people and hacking to take as impressive notes as you. Much appreciated!
