### ISSUE TITLE
[TOPIC] IBM Blog Post on Jupyter Ecosystem

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#16]
I think it ca deserve a link. 

http://blog.ibmjstart.net/2016/03/21/powered-by-jupyter/
## Jupyter Ecosystem

It's now starting to become a habit, `@parente` and `@lbustello` from IBM, wrote a beautiful summary of the Jupyter Ecosystem with many links to beautiful projects that integrating with Jupyter. We are just regretting one thing : Not having more time to explore all these links and not having a post like that everyday.

**Comment by minrk** [comment]
:+1:
