### ISSUE TITLE
Archive version of newsletter. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#17]
We need to have a place with the archive versions of the newsletter for people to read.

**Comment by willingc** [comment]
Perhaps a [nikola site](https://getnikola.com/) running on gh-pages.

**Comment by minrk** [comment]
I thought the newsletter was also going to get posted to the blog. Would that work?

**Comment by willingc** [comment]
That would work and be easier too.

**Comment by Carreau** [comment]
> I thought the newsletter was also going to get posted to the blog. Would that work?

Don't care which one.

> That would work and be easier too.

I'm not sure it's easier as you have to rewrite all in markdown, relink everything , reupload all the images,
and someone have to do it manually.

**Comment by Carreau** [comment]
Note, we use mailchimp, this can be done automatically:

http://kb.mailchimp.com/campaigns/archives/about-campaign-archives

**Comment by takluyver** [comment]
As we're creating them in this repo, I assumed that we'd archive them here (maybe with a nicer landing page linking to them).

**Comment by Carreau** [comment]
> As we're creating them in this repo, I assumed that we'd archive them here (maybe with a nicer landing page linking to them).

Does not change the fact that someone have to do that manually. The first newsletter was a draft here, 
was refined on a google doc, transferred to Mailchimp which  a WYSIWYM editor, and sent.

Which is not a workflow I'm found of, but for now is a reality. 

So we still have to set that up.

**Comment by katiewhite360** [comment]
*Brian and Ana had discussed putting the latest newsletter on the top of the blog and archiving the others in a tab on the same page..

**Yes the workflow needs to be changed..should we draft and refine here? That works for me, but I'm still getting familiar with github and so is Ana. We also aren't attatched to Mailchimp is there are other suggestions

**Comment by willingc** [comment]
Perhaps a workflow checklist might be a good start:
- [ ] Content submissions and ideas to GitHub
- [ ] Draft newsletter on GitHub
- [ ] Refine draft on Google Doc for publication
- [ ] Check in to GitHub and review final proof of newsletter  (+1 approvals on GitHub)
- [ ] Transfer final proof to MailChimp
- [ ] Distribute via MailChimp
- [ ] Archive automatically on MailChimp
- [ ] Archive final version on GitHub (this could be achieved without manual intervention after distribution if the review proof for newsletter was checked in and approved by +1's in GitHub)
- [ ] Post newsletter to blog and archive on blog (if desired) (Future enhancement?)

**Comment by Carreau** [comment]
> *Brian and Ana had discussed putting the latest newsletter on the top of the blog and archiving the others in a tab on the same page..

I want to avoid manual interaction, and having someone being the limiting factor. If mailchimp has archives, I don't see why we could not use them.

Let's keep current workflow for now, and refine slowly.

**Comment by willingc** [comment]
@katiewhite360 @Ruv7 @Carreau I updated the checklist of steps above. If you think this reflects the current process and like that process, let me know and I can help put together a draft document of the workflow process which you can edit as desired. Please use me as a resource for GitHub questions too.

**Comment by Carreau** [comment]
> Check in to GitHub and review final proof of newsletter (+1 approvals on GitHub)

Can we also share a Read-Only link to this draft on google docs ?

**Comment by Carreau** [comment]
Also, 

it **should** be possible to use Jekyll as a preview of the newsletter if it's written as markdown.

**Comment by Carreau** [comment]
@katiewhite360 did you enable the archive thing ? If so do you have a link ?
Publishing without archiving make it almost useless as no one can look at what they were goig to subscribe to. 

We should Not publish the next newsletter if these issues are not fixed.

**Comment by willingc** [comment]
Closing as addressed in #27.
