### ISSUE TITLE
[TOPIC] Link to oreilly Oriole

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#18]
Was finally announced today.
Todo: find link, but I'm on my phone right now.

**Comment by takluyver** [comment]
http://www.oreilly.com/oriole/

I'm already having to stop myself from mentally pronouncing it Oh-rye-uh-lee

**Comment by takluyver** [comment]
Also, cool - I had no idea this was in the works. I've just watched through Peter Norvig's regexes example. It's a really nice concept.

**Comment by willingc** [comment]
This is really cool.

**Comment by Carreau** [comment]
> Also, cool - I had no idea this was in the works. I've just watched through Peter Norvig's regexes example. It's a really nice concept.

Yeah, sorry, this was not really "secret", we had a demo a couple of weeks ago in BIDS, and last week at JupyterDays, with a friendly request not talk about it publicly.

**Comment by katiewhite360** [comment]
So are we just linking this?

**Comment by willingc** [comment]
Also this is their press release as well.

http://www.oreilly.com/pub/pr/3223

**Comment by Carreau** [comment]
> So are we just linking this?

Linking a write a few lines. I think it's enought.It goes well with the new peter norvig notebook posted last week. And the important part is that oriole use jupyter under the hood.
