### ISSUE TITLE
Get feedback from more people on newsletter draft. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/newsletter#22]
@katiewhite360 , please add more people to the draft each weeks, there are a few mistakes again that slipped through today. 

It's ok to make a newsletter every 3 weeks if 2 weeks is too short. We've always did things slowly but right, and not in a hurry.

**Comment by katiewhite360** [comment]
Will do.

Is the material still being gathered here?

**Comment by Carreau** [comment]
> Is the material still being gathered here?

Should be, just people seem to not contribute, and here in Berkeley we've been meeting for all of last week, and still a lot this week, so didn't had a chance to collect material. 

Also I can't and shouldn't be the only one to do that.

@ellisonbg any idea of who we can put on gathering material ?

**Comment by ellisonbg** [comment]
I fully agree that we can't have the collection/gathering be just one
person. Initially, it is going to have to be the entire core team (the
folks at the dev meeting). I don't see how we would delegate this to a
person outside this team as they are the ones who know everything going on.
Eventually, Jamie may have a good perspective on everything that is
happening, but we aren't there yet. My recommendation is to have myself and
@fperez work with Katie to send out an email to the core team every 2 weeks
with a reminder.

On Thu, Apr 7, 2016 at 9:59 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Is the material still being gathered here?
> 
> Should be, just people seem to not contribute, and here in Berkeley we've
> been meeting for all of last week, and still a lot this week, so didn't had
> a chance to collect material.
> 
> Also I can't and shouldn't be the only one to do that.
> 
> @ellisonbg https://github.com/ellisonbg any idea of who we can put on
> gathering material ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/22#issuecomment-206993966

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
Perhaps adding a reminder at the bottom of the weekly Dev Meeting HackPad for folks to make suggestions would be helpful as a weekly reminder.

**Comment by ellisonbg** [comment]
Yes! That is a perfect context for it as it already has a lot of that
content. Might also make sense for us to start asking folks to submit stuff
from their dev meeting report.

On Mon, Apr 11, 2016 at 5:51 PM, Carol Willing notifications@github.com
wrote:

> Perhaps adding a reminder at the bottom of the weekly Dev Meeting HackPad
> for folks to make suggestions would be helpful as a weekly reminder.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/22#issuecomment-208649792

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Ruv7** [comment]
No additional ideas were contributed today but we can keep trying for a few more weeks. Participation in this weeks meeting was fairly low so that may be to blame.

@katiewhite360  the Hackpad collection for Dev Meetings is here in case you're not familiar: https://jupyter.hackpad.com/collection/zCqMrBELzrv

**Comment by ellisonbg** [comment]
OK let's postpone the newsletter for this week - that will also give us
time to iterate on the process and tools

On Tue, Apr 12, 2016 at 2:20 PM, Ana Ruvalcaba notifications@github.com
wrote:

> No additional ideas were contributed today but we can keep trying for a
> few more weeks. Participation in this weeks meeting was fairly low so that
> may be to blame.
> 
> @katiewhite360 https://github.com/katiewhite360 the Hackpad collection
> for Dev Meetings is here in case you're not familiar:
> https://jupyter.hackpad.com/collection/zCqMrBELzrv
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/22#issuecomment-209107771

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
Here are a few:
1. Talk Python to Me podcast: Min and Matthias https://talkpython.fm/episodes/show/44/project-jupyter-and-ipython Has a good section on the history of Jupyter. Also a transcript is available.
2. Release of nbconvert https://groups.google.com/forum/#!topic/jupyter/Ea51RPt4FSU
3. Talks from first data science meetup at BIDs during the Dev Meeting https://bids.berkeley.edu/resources/videos/berkeley-data-science-meetup-all-about-jupyter
4. @parente's [10 New Reasons to use Jupyter in 10 minutes](http://nbviewer.jupyter.org/format/slides/gist/parente/4bc9dfa5ec529f53cc7e#/) slide deck

**Comment by katiewhite360** [comment]
Fantastic @willingc 

Has a Medium account been made? Content can go in anytime

**Comment by ellisonbg** [comment]
I am working on getting the passwords required to do that

**Comment by willingc** [comment]
Thanks @ellisonbg. I had no idea what the Medium account was.

**Comment by katiewhite360** [comment]
Oh yeah that wasn't directed at you Carol - sorry! 

Perfect, I'll have the content ready to go in when it's set up.

**Comment by willingc** [comment]
@katiewhite360 Don't leave me in suspense! What are you using the Medium account for?

**Comment by willingc** [comment]
@katiewhite360 :dog: :cat: :fish: :snake: I wonder if there is a Jupyter notebook about pets somewhere?

**Comment by katiewhite360** [comment]
We are trying Medium for publishing the newsletter because it takes a few steps out of the process (github>google docs>mailchimp>publish). It can be drafted, edited, published, and shared in the same place.

**Comment by willingc** [comment]
Makes sense to me @katiewhite360  Simplify all the things! Also, it's used quite a bit by open source bloggers and small publications.

Oh and I didn't find a notebook yet on pets but one link that came up was http://www.jesshamrick.com/2011/05/18/an-introduction-to-classes-and-inheritance-in-python/ @jhamrick :smile:

**Comment by katiewhite360** [comment]
Everybody loves cats and dogs!

**Comment by Carreau** [comment]
-1 on Medium.

**Comment by fperez** [comment]
I don't have a problem with Medium, and if it simplifies the workflow for
the folks doing the bulk of this work, I have no objections.

Matthias, do you see any major problems with it that are show stoppers? If
not, I suggest we let the team move forward with it for now, and see how it
goes.

My only question is in a different direction... Do we really have enough
content and bandwidth to do it every other week? I have the feeling we are
a bit overwhelmed as it is, and perhaps a monthly frequency might be easier
at least for a while?

**Comment by Carreau** [comment]
> Matthias, do you see any major problems with it that are show stoppers? If
> not, I suggest we let the team move forward with it for now, and see how it
> goes.

Just giving my take on that, last time I tried Medium, it was not that great either
for multiple collaborators, and it is one more things to keep track of.  

And it looks as another blog while we already have ghost.

If you want to try Medium, feel free to do so.

**Comment by ellisonbg** [comment]
The issues that Medium solves are this:
- It allows content to be authored in a single place rather than 3 (Google
  Docs for draft, Mail Chimp, and another place for archive).
- It handles both web based subscription/archiving and emailing those who
  are subscribed (like mail chimp)
- It has a notion of a publication that was editors and authors - this is
  exactly the editorial cycle that we have been missing with Ghost (which we
  were going to use for our archives).
- It not has a really nice API (I am going to have students work on a
  notebook to Ghost tool this summer).
- Right now there are a lot of things that Katie and Ana can't do well
  because of GitHub. We need to stop recommending GitHub for non-coding
  staff. It is a waste of time and leads to frustration.
- Medium now allow custom subdomains (newsletter.jupyter.org)
- Medium can allow for third party authors to submit content to
  publications for review and publication. Perfect for guest blog posts (if
  we were to migrate the blog as well).
- The content editor in Medium is amongst the best on the web - for
  non-coding people

All we are asking at this point is that we _try_ Medium - not to actually
publish a real newsletter, but for Katie and Ana to try the tool out and
see if it actually fixes the problems they have been having.

On Wed, Apr 13, 2016 at 1:38 AM, Fernando Perez notifications@github.com
wrote:

> I don't have a problem with Medium, and if it simplifies the workflow for
> the folks doing the bulk of this work, I have no objections.
> 
> Matthias, do you see any major problems with it that are show stoppers? If
> not, I suggest we let the team move forward with it for now, and see how it
> goes.
> 
> My only question is in a different direction... Do we really have enough
> content and bandwidth to do it every other week? I have the feeling we are
> a bit overwhelmed as it is, and perhaps a monthly frequency might be easier
> at least for a while?
> 
> On Wed, Apr 13, 2016, 01:01 Matthias Bussonnier notifications@github.com
> wrote:
> 
> > -1 on Medium.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/jupyter/newsletter/issues/22#issuecomment-209292725
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/22#issuecomment-209305367

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
Hi all, I've opened a PR with a draft of a [planning notebook](https://github.com/willingc/newsletter/blob/planning/planning/newsletter.ipynb). If you find it useful for framing discussion, please use it in the notebook form or another form. 

We have so much talent in this group and many balls to juggle. I want to make sure that we're being mindful of listening to each other's thoughts and seeing ideas from different perspectives. Simply, I wish to foster team communication at a pace that doesn't lead to burnout, tries to minimize unintentionally leaving people out of the loop, and avoids demotivating others. The notebook is merely a suggestion or catalyst to even better team ideas and actions.

**Comment by willingc** [comment]
cc/ @jamieshq FYI

**Comment by fperez** [comment]
Ok, given that:

a) Matthias objection wasn't strenuous nor based on a show-stopper issue.
b) There seems to be real interest in trying out Medium by the folks
carrying a lot of this burden, and it seems to address real issues we do
have.

I'd like to call it to move forward with trying it out for the newsletter.
I know we're bad at calling decisions, so let me try to help with that at
least :)

If we end up super-duper-happy with it after a few months of using it for
that, we can rethink the blog itself, but let's not worry about that for
now.

**Comment by ellisonbg** [comment]
Almost concurrently we Fernando sending this out - I sent out a message to
those folks directly working on the newsletter with information about us
trying out medium. For now. I don't even think we want to commit to using
it officially. Katie has some questions about how it will work for
something like this - we will probably just do a private test run with a
few people and if that goes well, think about doing it for a published
newsletter (with a custom subdomain, have Cameron design us a banner, pick
colors, etc.).

On Wed, Apr 13, 2016 at 3:41 PM, Fernando Perez notifications@github.com
wrote:

> Ok, given that:
> 
> a) Matthias objection wasn't strenuous nor based on a show-stopper issue.
> b) There seems to be real interest in trying out Medium by the folks
> carrying a lot of this burden, and it seems to address real issues we do
> have.
> 
> I'd like to call it to move forward with trying it out for the newsletter.
> I know we're bad at calling decisions, so let me try to help with that at
> least :)
> 
> If we end up super-duper-happy with it after a few months of using it for
> that, we can rethink the blog itself, but let's not worry about that for
> now.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/22#issuecomment-209678337

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
