### ISSUE TITLE
Medium Testing

### ISSUE THREAD

**Issue by Ruv7** [jupyter/newsletter#26]
Here is the list of open issues for the next iteration of the newsletter. My goal is to work through these open issues tomorrow and publish Wednesday if at all feasible and Thursday at the latest.
- draft of Hello World (1st edition) and ++ (2nd edition) are loaded and ready for comment, simply highlight a word or sentence and you will get a pop up that will allow you to insert a comment. Comments show up on the right hand side of the page and can be responded to or deleted. Let me know if you see any issues, these will serve as the archives for the newsletter and only be sent for testing purposes to Fernando, Brian, Carol, Jamie, Cameron, Katie, and myself. 

Hello World: https://medium.com/@katiewhite360/8b4ab6ab356
++: https://medium.com/@katiewhite360/25455d4792ad
- @ellisonbg Brian: pending action is to create custom domain and to provide direction to @cameronoelsen on creating an image or images for the posts, design review in general would be good I see part of the logo getting cut off on the Project Jupyter user profile: https://medium.com/@ProjectJupyter
- @fperez @cameronoelsen and @Carreau please follow the Jupyter Newsletter and https://medium.com/jupyter-newsletter - thanks to @willingc and @JamiesHQ I see you on the list
- @katiewhite360  is in the process of finalizing content for newsletter 3 and figuring out whether we can publish a letter after we publish/post a story. Currently we can send a letter to our followers which automatically posts or publishes a story. 
- answer to the question above affects newsletter building process
- known issue with a letter versus publishing a story is that it is inserts a link instead of embedding the image of the YouTube video at the bottom of the newsletter

@katiewhite360 if there is anything else I'm missing from the list please add comments. Thx.

**Comment by fperez** [comment]
Mmh, I'm already following, and did so right away when Katie pinged us:

![image](https://cloud.githubusercontent.com/assets/57394/14974255/8a0e03ce-10a7-11e6-9023-02e76a449994.png)

am I not appearing in your list?

**Comment by willingc** [comment]
@fperez Looks like there are two to be following: Project Jupyter (the one you are following) and [Jupyter Newsletter](https://medium.com/jupyter-newsletter/about).

Is it a possibility to send the newsletter from the Project Jupyter Medium since it already has followers?

**Comment by ellisonbg** [comment]
You may have to follow the publication separately

**Comment by fperez** [comment]
Ok, I've followed the newsletter:

![image](https://cloud.githubusercontent.com/assets/57394/14978487/fb8d3276-10d0-11e6-99de-7b835cb8359f.png)

and yet when I go to my profile, it says I'm not following it:

![image](https://cloud.githubusercontent.com/assets/57394/14978502/154dfe7a-10d1-11e6-8668-e4b84a039c4e.png)

I don't know why that would be the case...

**Comment by willingc** [comment]
> I don't know why that would be the case...

@fperez I have the same profile following experience as you. Perhaps since the newsletter is still in draft and not yet released.

**Comment by ellisonbg** [comment]
Great. A few points of clarification:
- Let's publish Newsletters 1 and 2 as tests, before we commit to this
  publicly and create a new subdomain.
- I shouldn't be the one to create the subdomain. Min, Thomas or Matthias
  would be much better to do that.

On Tue, May 3, 2016 at 4:52 AM, Carol Willing notifications@github.com
wrote:

> I don't know why that would be the case...
> 
> @fperez https://github.com/fperez I have the same profile following
> experience as you. Perhaps since the newsletter is still in draft and not
> yet released.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/26#issuecomment-216505791

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Ruv7** [comment]
Ok, thanks. I have published one letter each for Newsletter 1 and 2 which generates an email to all followers (that have this feature enabled) and a story to the Jupyter Newsletter publication.

**Comment by Ruv7** [comment]
For @cameronoelsen - some notes on specs for Medium images https://help.medium.com/hc/en-us/articles/216770578-Publication-images

**Comment by Ruv7** [comment]
@jamieshq - here is how you edit a story once its published.  https://help.medium.com/hc/en-us/articles/215194537-Edit-a-published-story

**Comment by ellisonbg** [comment]
The emails that I got with the first 2 looked great!

On Tue, May 3, 2016 at 1:40 PM, Ana Ruvalcaba notifications@github.com
wrote:

> @jamieshq https://github.com/jamieshq - here is how you edit a story
> once its published.
> https://help.medium.com/hc/en-us/articles/215194537-Edit-a-published-story
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/26#issuecomment-216657765

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
I'm notorious for shutting off all notifications and emails, but I looked at them online and they looked good. I also favorited the individual posts and left a comment about Interactive Blog Posts with Jupyter.

**Comment by fperez** [comment]
+1, emails look great, and with an easy to find  link to the static web version that can serve as the permanent record (which we can tweet, etc).  Test looking good so far, thanks!

**Comment by Ruv7** [comment]
I want to flag a couple things: 
- Due to version control issues there should only be one editor with permissions on any given story. This is because any editor can make changes and it will not be visible to other editors.
- Depending on how many Medium followers allow letters [they can turn this feature off]  we may potentially instantly have a following of about 2k readers (from Twitter integration) who have the ability to comment and highlight any part of our posts. This means our editing game and review process needs to be on point. Not that it didn't need to be before but mistakes will be much more visible now. 
- I'd love to have a technical co-leader on this project that would be responsible twice a month for reviewing the entire newsletter draft and on an ongoing basis serve as a sounding board in providing feedback on how to present our newsletter in a way that is appealing to technical users. I would handle letter creation, non technical editing, and deployment.

Here is the list of pending items: 
1. Pending response from Medium: I'm waiting for a response from Medium support on how to embed a you tube video into a letter. This is rendering correctly in the web interface but not in the email letter which contains a medium link instead.
2. Pending response from Brian/Cameron: Design review on Jupyter Newsletter (publication) and Project Jupyter (user) - would need to happen today or tomorrow if we are to make this weeks publication goal. We can publish one more time in Mail Chimp if this is not reasonable. We now have a one month gap in publication. Last issues of the newsletter were generated on March 15 and March 30.
3. Pending request to Min/Thomas/Matthias to create subdomain. This will be made once we decide to move forward on publishing the newsletter in Medium. Would need to happen today or tomorrow if we are to make this weeks publication goal.
4. Pending from Ana: figure out best way to give contributors credit for authoring/editing posts. Currently anyone who makes a comment that is accepted automatically gets credit at the bottom of the post but I need to see if there are other ways. I also need to create short description or a tweet for those who want to sign up for the newsletter. I'll do this once we fully decide to use Medium. Note there is an integration with Twitter and Medium that allows us to migrate 1.8k followers on Twitter who have Medium accounts. https://help.medium.com/hc/en-us/articles/216543767-Connect-Twitter-to-your-publication

**Comment by ellisonbg** [comment]
Ana, thanks for the update!

I think we should make the official decision to use Medium (or not).
@fperez how do you want to make this? I am in favor of using Medium for
this.

>    -
> 
>    Due to version control issues there should only be one editor with
>    permissions on any given story. This is because any editor can make changes
>    and it will not be visible to other editors.
> 
> Just want to clarify - I one editor makes changes, the other editors can
> see the changes in the document, but there is no way of knowing how the
> document was changed exactly. It is not like the changes are discarded
> right?

We run into this same issue with editing Google Docs as well (if comments
are not used, which we often don't). Our usual approach is to have multiple
people take a pass and if there are things that need discussing, we just
leave a comments as bold text in the document. Summary - as long as we have
a semi-formal process of who edits the posts, I think we can and should
have multiple editors.

>    -
> 
>    Depending on how many Medium followers allow letters [they can turn
>    this feature off] we may potentially instantly have a following of about 2k
>    readers (from Twitter integration) who have the ability to comment and
>    highlight any part of our posts. This means our editing game and review
>    process needs to be on point. Not that it didn't need to be before but
>    mistakes will be much more visible now.
>    -
> 
>    I'd love to have a technical co-leader on this project that would be
>    responsible twice a month for reviewing the entire newsletter draft and on
>    an ongoing basis serve as a sounding board in providing feedback on how to
>    present our newsletter in a way that is appealing to technical users. I
>    would handle letter creation, non technical editing, and deployment.
> 
> I think we want to have 2-3 people able to help with the technical editing
> so we don't run into problems with people being unavailable because of
> travel. I am more than willing to help edit these.
> 
> Here is the list of pending items:
> 
>    1.
> 
>    Pending response from Medium: I'm waiting for a response from Medium
>    support on how to embed a you tube video into a letter. This is rendering
>    correctly in the web interface but not in the email letter which contains a
>    medium link instead.
>    2.
> 
>    Pending response from Brian/Cameron: Design review on Jupyter
>    Newsletter (publication) and Project Jupyter (user) - would need to happen
>    today or tomorrow if we are to make this weeks publication goal. We can
>    publish one more time in Mail Chimp if this is not reasonable. We now have
>    a one month gap in publication. Last issues of the newsletter were
>    generated on March 15 and March 30.
>    3.
> 
>    Pending request to Min/Thomas/Matthias to create subdomain. This will
>    be made once we decide to move forward on publishing the newsletter in
>    Medium. Would need to happen today or tomorrow if we are to make this weeks
>    publication goal.
>    4.
> 
>    Pending from Ana: figure out best way to give contributors credit for
>    authoring/editing posts. Currently anyone who makes a comment that is
>    accepted automatically gets credit at the bottom of the post but I need to
>    see if there are other ways. I also need to create short description or a
>    tweet for those who want to sign up for the newsletter. I'll do this once
>    we fully decide to use Medium. Note there is an integration with Twitter
>    and Medium that allows us to migrate 1.8k followers on Twitter who have
>    Medium accounts.
>    https://help.medium.com/hc/en-us/articles/216543767-Connect-Twitter-to-your-publication
> 
> I think we should hold off on the deadline for a few days to let us do the
> 3rd one on Medium with the new subdomain - a few extra days delay aren't
> going to hurt in this case and it would be a shame to have to go back to
> the old workflow.
> 
>    1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/newsletter/issues/26#issuecomment-216685398

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Ruv7** [comment]
Yes, correct on the edits q. It's like a word doc with no tracking on. All editors can make changes which are saved to the original document. There is a time stamp for changes but it won't show who made the changes or what changes were made. 

If no one technical person co-leads this effort it feels more challenging for me to project manage efficiently but I agree it's great to have multiple technical editors available in case that person is unavailable. Maybe one person leads the effort and we have a backup in place? There really is only a handful of you guys who would be able to do this anyway.

I will work with Katie to create a timeline that includes content/review/publishing deadlines for the next three months and then we can make a call on this. This is really only happening twice a month.

At the very least I would ask that we keep one technical editor per post. Word choice and flow at times are simply personal preference and I don't recommend multiple people edit at the same time since one editor may make changes that the other editor just updated. 

Per our conversation I will be working with Cameron today on design of images and our user account.

**Comment by Ruv7** [comment]
ps. we cannot at this embed a youtube video in a letter. This will need to go as a link in the letter but will show up as a clickable video in the story

**Comment by fperez** [comment]
My suggestion for the decision: Ana, could you ping the list with a brief message asking folks to come over to issue #27 to indicate if they have any preference?  That way we can keep the longer back-story here and tally votes there. Let's try that as a mechanism for quickly collecting yes/no input using the vote emojis :)

**Comment by Ruv7** [comment]
That works, thanks
