### ISSUE TITLE
Clear out Open issues 

### ISSUE THREAD

**Issue by Ruv7** [jupyter/newsletter#29]
@katiewhite360 - as you're able can you please look through all open issues on the newsletter repo and close out anything that doesn't need further discussion? Note you can always reopen these if you need to. I closed out several but if you can help with the remaining that would be great. Also do you have a cue of topics/write ups for future newsletters is being stored? Can you share this or create an issue?

**Comment by Ruv7** [comment]
Thanks @willingc for clearing out a few of these also!

**Comment by willingc** [comment]
@katiewhite360 @Ruv7 I'm closing since there appears to be no further action now.
