### ISSUE TITLE
Create archive directory and use git-lfs to store content

### ISSUE THREAD

**Issue by willingc** [jupyter/newsletter#33]
Create an archive directory and use [git-lfs](https://git-lfs.github.com/) to efficiently store content (images, media, zip files, pdfs) for archive.

@katiewhite360 @Ruv7 Ping me after the next newsletter is published and I'll archive the issues.

@rgbkrk Anything special that I need to do for the repo other than set the .git-attributes for the large format file types that we will use. I've got the git-lfs client on my machine and have used it with other repos. Thanks.

**Comment by rgbkrk** [comment]
Once users have lfs installed, when they know they want to version something with lfs that isn't already tracked, they need to run, e.g. `git lfs track "*.sketch"`. That updates the `.gitattributes` file for you. The hardest part of that burden is getting all contributors to install LFS, though they can use the repo without it.

**Comment by willingc** [comment]
@rgbkrk Thanks!
