### ISSUE TITLE
Newsletter Timeline: Drop Date 07/20/2016

### ISSUE THREAD

**Issue by katiewhite360** [jupyter/newsletter#39]
06/29/2016  - Wednesday - Deadline for content submission

07/05/2016 -Tuesday - Select topics and outline first draft

07/05/2016 - Tuesday  - Send initial draft to editors on medium, technical review  

07/13/2016 - Wednesday - Feedback due from editors. Make graphic request to design team

07/15/2016 - Friday - Graphic Due

07/19/2016 - Tuesday - Run Test: Send letter, Final Review

07/20/2016  - Wednesday  - Publish

@ellisonbg @fperez @Carreau @willingc

**Comment by Carreau** [comment]
Side question: 

https://medium.com/@projectJupyter

Does not list any of the archived newsletter. Which IIRC was the point of doing that on Medium IIUC. Am I missing something. 

There still a draft "DO NOT EDIT THIS VERSION" can it be deleted ?

**Comment by katiewhite360** [comment]
We are archiving the newsletters in the 'Jupyter Newsletter' Medium account, which is separate from the 'Project Jupyter' account (and very confusing) 

I'll delete the DO NOT EDIT version. Thanks for flagging that for me!

**Comment by Carreau** [comment]
Ah... Yes, confusing.

we definitively need a link to that.

The template could probably have a "See past newsletter and subscribe to

## new one at https://newsletter.jupyter.org/"

M

**Comment by willingc** [comment]
FYI all, PDFs of the newsletters are being archived in this repo as well https://github.com/jupyter/newsletter/tree/master/archives

**Comment by parente** [comment]
From standup today: @lbustelo, @parente to comment here with a bit about the enhancement proposals for dashboards and declarative widgets.

**Comment by Ruv7** [comment]
@katiewhite360 - note the content Gino & Peter from the post immediately above should be included in the next newsletter scheduled to drop on 7/20 since they are looking for feedback on the work they're doing - lmk if you have any questions since this was discussed in a call today. Thanks!

**Comment by lbustelo** [comment]
The [jupyter-declarativewidgets](https://github.com/jupyter-incubator/declarativewidgets) extension enables the user to create interactive areas of the Notebook that connect to functions and data on the kernel. It works on top of Python, Scala and R.

In conjunction with the [jupyter-dashboard](https://github.com/jupyter-incubator/dashboards) extension and related sub-projects, it is possible to turn Notebooks into full-featured dashboards and applications.

**Comment by parente** [comment]
The [jupyter-dashboards extension](https://github.com/jupyter-incubator/dashboards) lets users arrange notebook outputs and widgets in grid- and report-like layouts. It is the first of three capabilities in the [Jupyter Incubator Dashboards effort](https://github.com/jupyter-incubator/dashboards/wiki) and a nice compliment to the [jupyter-declarativewidgets](https://github.com/jupyter-incubator/declarativewidgets).

The dashboard project developers recently proposed making the extension a top-level Jupyter project. [Give it a try](jupyter.cloudet.xyz) and provide your feedback on [the incorporation proposal](https://github.com/jupyter/enhancement-proposals/pull/17).

**Comment by katiewhite360** [comment]
Thanks @parente and @lbustelo ! 

Could I get a header and an image for both of these, ideally by Friday?

**Comment by Ruv7** [comment]
Though if an image doesn't enhance the content or one doesn't exist that's fine too...

**Comment by parente** [comment]
@katiewhite360 would the image in the readme in the dashboards extension repo linked above do? It's showcasing both the widgets and the dashboard layout.

**Comment by katiewhite360** [comment]
That's perfect. A header? 

Thanks!

**Comment by katiewhite360** [comment]
Just a reminder for headers - could even be anything 5-10 words. @parente @lbustelo

**Comment by parente** [comment]
@katiewhite360 Ah, sorry. I thought you meant header image.

How about one of these? You can choose or wordsmith.
- A new way to consume notebooks with dashboards and declarative widgets
- Cross language widgets and dashboard layouts for Jupyter notebooks
- Incubating Jupyter declarative widgets and dashboard projects ready to graduate

**Comment by willingc** [comment]
Dashboard and declarative widgets projects graduating from Jupyter incubator

@katiewhite360 @parente What about this one?
