### ISSUE TITLE
NGCM summer academy

### ISSUE THREAD

**Issue by takluyver** [jupyter/newsletter#41]
I'm not really sure where to add content, so here's a bit on the summer academy.

> Min Ragan-Kelley and Thomas Kluyver taught a two day workshop on Jupyter and IPython at the NGCM (next generation computational modelling) summer academy in June. PhD students from around the UK came to Southampton for the week-long course, which also included topics such as data analysis with pandas, 3D visualisation with VTK, and GPU programming with CUDA. We hope to be invited back in 2017 to give an updated version of the workshop.

I've got permission to use [this picture](https://pbs.twimg.com/media/Clehq_dWYAQ0-cD.jpg:large) if we credit the photographer, [Bob Entwhistle](https://twitter.com/b_entwistle).

@minrk: anything we should add to that?

**Comment by katiewhite360** [comment]
Thanks! Can I get a header for this, and are there any videos of the workshop? @takluyver

**Comment by willingc** [comment]
@takluyver I sent @katiewhite360 some info about the workshop a few days ago (link to website and the repo for background). Nice photo. Isn't there one of you too? ;-)

**Comment by katiewhite360** [comment]
@willingc in that email you mentioned a video in one of the links but I wasn't able to find it...am I missing something or was it not recorded?

**Comment by takluyver** [comment]
Header: Workshop in Southampton (?)

I don't know of any video from it - the workshops weren't being recorded like a conference. And I didn't find any photos of the two of us together.

**Comment by katiewhite360** [comment]
That's ok this picture works well :)    Thanks @takluyver @willingc !

**Comment by willingc** [comment]
Ah...the video was on the page and was of Vanessa Graber talking about the entire NGCM experience and benefits https://www.youtube.com/watch?v=A_4piuBzpjQ

@takluyver We'll have to wait for the next event for a photo of the presenting duo.

**Comment by takluyver** [comment]
It may even be a different duo next year. Fernando's promised to make it one year...
