### ISSUE TITLE
Newsletter Draft for Editing: Drop Date 07/20/2016

### ISSUE THREAD

**Issue by katiewhite360** [jupyter/newsletter#42]
Hello all, 

Please look over the content of this newsletter for edits - especially the "Dashboard and Declarative Widget Projects Graduating from Jupyter Incubator" section. Also, note that some of the content about SciPy (which ends right before the drop date) is filled in now by placeholders and will be written/edited at the conference. Edits can be made directly to the letter - I have a saved copy of the original version. 
Here is the link: [https://medium.com/jupyter-newsletter/letters] 
Click on the draft titled "Jupyter Newsletter 5 • July 20" 

The deadline for feedback is Wednesday, 07/13 and we will send a test of the final version on Tuesday, 07/19. 

Thanks again, 
- Katie 

@Carreau @ellisonbg @willingc @JamiesHQ @fperez

**Comment by Carreau** [comment]
@bollwyvl want to add Jupyter Days atlanta in "events" ?
