### ISSUE TITLE
Newsletter Timeline: Drop Date 08/24/2016

### ISSUE THREAD

**Issue by katiewhite360** [jupyter/newsletter#43]
07/29/2016 - Friday - Deadline for content submission 

80/04/2016 - Thursday - Send initial draft to editors on Medium, technical review

80/17/2016 - Wednesday - Feedback due from editors. Make graphic request of design team

08/19/2016 - Friday - Graphic Due 

08/23/2016 - Tuesday - Run Test: Send letter to editors 

08/24/2016 - Wednesday - Publish

Put your content ideas in "Newsletter Content Ideas: Drop Date 08/24/2016" or email them to katiewhite360@gmail.com. Thanks! 

@Carreau @ellisonbg @willingc @fperez @Ruv7

**Comment by Ruv7** [comment]
@katiewhite360 - hi there! can please clarify the second and third line item from your timeline above? was the initial draft supposed to come out today or did it go out last Thursday and I missed it? let me know, thanks

**Comment by Ruv7** [comment]
@katiewhite360 - I've called, texted, emailed, and githubbed. If you hadn't checked in your time on Kronos I would have called your emergency contact by now. I may or may not have watched one too many 48 hours. Ha. Given the timeline above calls for publishing this next week I will assume we're not going to hit that target. I know you had interviewed and done a ton of work related to SciPy happenings - do you want to push back this deadline or should I move on to creating a draft myself? Obviously, we won't have your content and some expectations may have been set by the people you interviewed for the issue. Let me know how you want to proceed. If you are unable to work on the newsletter I would ask that you let me know asap so I can make a plan to publish with different content.

**Comment by Ruv7** [comment]
Moving the discussion to a new issue since we're re-working the timeline.
