### ISSUE TITLE
Newsletter Content Suggestion

### ISSUE THREAD

**Issue by Kacawi-zz** [jupyter/newsletter#53]
### Summary of story:

An easy-to-follow tutorial for beginners that explains how to install and run the Jupyter Notebook Application and how it can be used as an interactive environment for data science. The tutorial includes tips and best practices to use Jupyter Notebooks efficiently on your own or in data science teams, and examples of Jupyter Notebooks that will inspire new users. 

### Link(s) to additional information:

[Jupyter Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)

### Other information about the story: NA

**Comment by Ruv7** [comment]
Hello @Kacawi - thanks for the suggestion! I will include this in the draft for the December iteration of the newsletter. The suggested copy goes to a small group of editors who decide on final content. I will post here as we get closer to the drop date to let you know if we can include your tutorial. Hope you enjoy the rest of your week! Let me know if you have any questions or further comments.

**Comment by Kacawi-zz** [comment]
Hi @Ruv7 , thank you very much for taking the tutorial into consideration! Have a great week too and hear from you soon! :)

**Comment by Ruv7** [comment]
Hi @Kacawi - I hope you're enjoying the holidays and I apologize for the delay in reaching out. Good news - your story made it into the newsletter. This went out on December 21 and you can see it here in case you didn't catch the announcement on Twitter. https://newsletter.jupyter.org/jupyter-newsletter-10-december-21-2016-a8f86919196f#.yh1qbw4ke

**Comment by Kacawi-zz** [comment]
Hi @Ruv7 , I indeed caught the announcement and was delighted to see the tutorial mentioned! Thank very much for everything! Happy holidays and a fantastic 2017 (already well in advance :)).
