### ISSUE TITLE
nbdime announcement

### ISSUE THREAD

**Issue by minrk** [jupyter/newsletter#56]
We've just published the first release of nbdime: tools for diffing and merging notebooks. nbdime provides tools for viewing diffs of notebooks in the terminal, viewing rich diffs in a browser, automatically resolving merge conflicts, and a web-based tool for three-way merging of notebooks. [Check it out](https://nbdime.readthedocs.io), let us know how it goes, and help out if you can! This work is led by Martin Alnæs and Vidar Fauske at Simula Research Laboratory, and supported by the [OpenDreamKit](http://opendreamkit.org) project, funded by the EU H2020 program.

**Comment by willingc** [comment]
@Ruv7 Any chance to get this in the current issue? It's pretty cool.

**Comment by Ruv7** [comment]
Yes, this is great! Thanks Min.

**Comment by Ruv7** [comment]
Included in the December newsletter.
